// <auto-generated />
using System;
using Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(ManticoreContext))]
    [Migration("20260603210248_InitialManticoreMigration")]
    partial class InitialManticoreMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Backend.Models.Produkt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cena")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Kategoria")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Opis")
                        .HasColumnType("longtext");

                    b.Property<string>("Zdjecie")
                        .HasColumnType("longtext")
                        .HasColumnName("zdjęcie");

                    b.HasKey("Id");

                    b.ToTable("produkty", (string)null);
                });

            modelBuilder.Entity("Backend.Models.Restauracja", b =>
                {
                    b.Property<int>("Nr_restauracji")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Nr_restauracji"));

                    b.Property<decimal>("Dlugosc_geo")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Miejscowosc")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Nr_budynku")
                        .HasColumnType("int");

                    b.Property<int?>("Nr_lokalu")
                        .HasColumnType("int");

                    b.Property<decimal>("Szerokosc_geo")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Ulica")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Zdjecie")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Nr_restauracji");

                    b.ToTable("restauracje", (string)null);
                });

            modelBuilder.Entity("Backend.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("users", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
